# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 46a5ed85992bc4ad14ebe9694c1f4f9beca2051b2afbaaa2a5ece130a5642000
    docker:
      # specify the version you desire here
      - image: python:3.8
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run flake8!
      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            flake8 ./

      - run:
          name: Run tests
          command: |          
            . venv/bin/activate
            coverage run --source='.' manage.py test
            coverage report --omit='venv/*'
            coverage xml --omit='venv/*'

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - deploy:
          branch: master
          command: |
            . venv/bin/activate
            fab staging git_pull
            fab staging install_requirements
            fab staging deploy
            fab staging migrate
            fab staging restart_server
