# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='migrate@example.org', max_length=254),
            preserve_default=False,
        ),
    ]
