# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20171125_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position_type',
            field=models.CharField(blank=True, choices=[('board_1', '1. Vorsitzender'), ('board_2', '2. Vorsitzender'), ('board_3', 'Finanzvorstand')], max_length=50, null=True, verbose_name='Position im Verein'),
        ),
    ]
