# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_member_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateTimeField(verbose_name='Mitlied seit'),
        ),
    ]
