# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20171126_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='application_form',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.MemberApplication', verbose_name='Mitgliedsantrag'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position_type',
            field=models.CharField(blank=True, choices=[('board_1', '1. Vorsitzender'), ('board_2', '2. Vorsitzender'), ('board_3', 'Finanzvorstand')], max_length=50, null=True, verbose_name='Position im Vorstand'),
        ),
    ]
