# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20171126_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-last_name'], 'verbose_name': 'Mitglied', 'verbose_name_plural': 'Mitglieder'},
        ),
    ]
