# Generated by Django 2.0 on 2018-01-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20171226_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid_2018',
            field=models.BooleanField(default=False, verbose_name='bezahlt 2018?'),
        ),
    ]
