# Generated by Django 2.0.2 on 2018-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_member_paid_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('active', 'Aktiv'), ('active_cheerleading', 'Aktiv - Cheerleading'), ('support', 'Fördermitglied'), ('inactive', 'Ausgetreten')], max_length=50, verbose_name='Art der Mitgliedschaft'),
        ),
    ]
