# Generated by Django 2.0.2 on 2018-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_auto_20180225_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid_2019',
            field=models.BooleanField(default=False, verbose_name='bezahlt 2019?'),
        ),
    ]
