# Generated by Django 2.0.2 on 2019-12-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_member_paid_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid_2020',
            field=models.BooleanField(default=False, verbose_name='bezahlt 2020?'),
        ),
    ]
