# Generated by Django 3.0.1 on 2020-01-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_member_paid_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='paid_2018',
            field=models.NullBooleanField(default=False, verbose_name='bezahlt 2018?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_2019',
            field=models.NullBooleanField(default=False, verbose_name='bezahlt 2019?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_2020',
            field=models.NullBooleanField(default=False, verbose_name='bezahlt 2020?'),
        ),
    ]
