# Generated by Django 3.1.3 on 2020-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20200119_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid_2021',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2021?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_2018',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2018?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_2019',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2019?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_2020',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2020?'),
        ),
    ]
