# Generated by Django 3.1.3 on 2022-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_auto_20201103_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid_2022',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2022?'),
        ),
    ]
