# Generated by Django 5.2.6 on 2025-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_alter_member_gender_alter_member_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_exited',
            field=models.DateField(blank=True, null=True, verbose_name='Ausgetreten zum'),
        ),
        migrations.AddField(
            model_name='member',
            name='paid_2024',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2024?'),
        ),
        migrations.AddField(
            model_name='member',
            name='paid_2025',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2025?'),
        ),
        migrations.AddField(
            model_name='member',
            name='paid_2026',
            field=models.BooleanField(default=False, null=True, verbose_name='bezahlt 2026?'),
        ),
    ]
