# Generated by Django 5.2.6 on 2025-09-10 16:20

from django.db import migrations, models


def populate_sepa_date(apps, schema_editor):
    Member = apps.get_model("yourappname", "Member")

    for member in Member.objects.all().select_related("application_form"):
        if member.application_form and member.application_form.created_at:
            member.sepa_date = member.application_form.created_at.date()
            member.save(update_fields=["sepa_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_member_member_exited_member_paid_2024_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sepa_date',
            field=models.DateField(blank=True, null=True, verbose_name='SEPA-Mandatsdatum'),
        ),
        migrations.RunPython(populate_sepa_date, reverse_code=migrations.RunPython.noop),
    ]
