# Generated by Django 5.2.7 on 2025-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_member_sepa_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sepa_ok',
            field=models.BooleanField(default=True, null=True, verbose_name='SEPA OK?'),
        ),
    ]
