# Generated by Django 5.2.7 on 2025-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_member_sepa_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='student_status',
            field=models.CharField(blank=True, choices=[('tum', 'TUM'), ('lmu', 'LMU'), ('other_university', 'Andere Universität'), ('apprenticeship', 'Ausbildung'), ('working', 'Berufstätig')], max_length=50, null=True, verbose_name='Student Status'),
        ),
    ]
