# Generated by Django 5.2.7 on 2025-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_member_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mahnungsstatus',
            field=models.CharField(blank=True, choices=[('erinnerung', 'Erinnerung'), ('mahnung_1', '1. Mahnung'), ('mahnung_2', '2. Mahnung'), ('mahnung_3', '3. Mahnung')], max_length=50, null=True, verbose_name='Mahnungsstatus'),
        ),
    ]
