# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_memberapplication_is_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberapplication',
            options={'verbose_name': 'Mitgliedsantrag', 'verbose_name_plural': 'Mitgliedsantr\xe4ge'},
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='birthday',
            field=models.DateField(verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Adresse'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='is_new',
            field=models.BooleanField(default=True, editable=False, verbose_name='neu ?'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='membership_type',
            field=models.CharField(choices=[('active', 'Aktiv'), ('active_cheerleading', 'Aktiv - Cheerleading'), ('support', 'F\xf6rdermitglied')], max_length=50, verbose_name='Art der Mitgliedschaft'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='postal_code',
            field=models.CharField(max_length=25, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='street_name',
            field=models.CharField(max_length=100, verbose_name='Stra\xdfe'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='street_number',
            field=models.CharField(max_length=25, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='ge\xe4ndert am'),
        ),
    ]
