# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20171125_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='wants_to_be_memeber',
            field=models.BooleanField(default=False, verbose_name='Ich möchte zum nächstmöglichen Zeitpunkt Mitglied im Studylife München e.V werden.'),
        ),
    ]
