# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_memberapplication_wants_to_be_memeber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberapplication',
            old_name='wants_to_be_memeber',
            new_name='wants_to_be_member',
        ),
    ]
