# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:56


from django.db import migrations, models
from django.utils.crypto import get_random_string


def update_verify(apps, schema_editor):
    MemberApplication = apps.get_model("application", "MemberApplication")
    for application in MemberApplication.objects.all():
        application.verification_code = get_random_string(64)
        application.save()


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0010_memberapplication_verification_code'),
    ]

    operations = [
        migrations.RunPython(update_verify)
    ]
