# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_data_migration_for_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberapplication',
            name='verification_code',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
