# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20171127_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='is_verified',
            field=models.BooleanField(default=True, editable=False, verbose_name='Bestätigt via Email ?'),
        ),
    ]
