# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 17:36


import localflavor.generic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_memberapplication_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='bic',
            field=localflavor.generic.models.BICField(blank=True, max_length=11, null=True, verbose_name='Deine BIC'),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='gender',
            field=models.CharField(choices=[('female', 'Frau'), ('male', 'Mann')], max_length=50, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='iban',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, null=True, use_nordea_extensions=False, verbose_name='Deine IBAN'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='country',
            field=models.CharField(default='Deutschland', max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='is_verified',
            field=models.BooleanField(default=False, editable=False, verbose_name='Bestätigt via Email ?'),
        ),
    ]
