# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 19:43
from __future__ import unicode_literals

import application.models
from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20171219_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberapplication',
            name='bic',
            field=localflavor.generic.models.BICField(max_length=11, null=True, verbose_name='Deine BIC'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='city',
            field=models.CharField(help_text='Bitte die Münchner Adresse angeben (falls vorhanden).', max_length=100, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail Adresse'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, null=True, use_nordea_extensions=False, verbose_name='Deine IBAN'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='postal_code',
            field=models.CharField(help_text='Bitte die Münchner Adresse angeben (falls vorhanden).', max_length=25, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='street_name',
            field=models.CharField(help_text='Bitte die Münchner Adresse angeben (falls vorhanden).', max_length=100, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='street_number',
            field=models.CharField(help_text='Bitte die Münchner Adresse angeben (falls vorhanden).', max_length=25, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='wants_to_be_member',
            field=models.BooleanField(default=False, validators=[application.models.validate_true]),
        ),
    ]
