# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[(1, 'Vorstandsbenachrichtigung für neuen Mitgliedsantrag'), (2, 'Vorstandsbenachrichtigung für bestätigte bestätigte Email'), (3, 'Email mit Bestätigungslink'), (4, 'Bestätigung der Mitgliedschaft')], max_length=100, unique=True, verbose_name='Template-Typ')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
