# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 01:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('notify_board_new_application', 'Vorstandsbenachrichtigung für neuen Mitgliedsantrag'), ('notify_board_verified_application', 'Vorstandsbenachrichtigung für bestätigte bestätigte Email'), ('notify_member_to_verify_application', 'Email mit Bestätigungslink'), ('notify_member_about_application', 'Bestätigung der Mitgliedschaft')], max_length=100, unique=True, verbose_name='Template-Typ'),
        ),
    ]
