# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0002_auto_20171227_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='', max_length=250, verbose_name='Betreff'),
            preserve_default=False,
        ),
    ]
